#!/usr/bin/env python2
# -*- coding: utf8 -*-

# Built-in modules #
import sys, argparse

# Internal modules #
import seqenv

# Parse the shell arguments #
parser = argparse.ArgumentParser(description=sys.modules[__name__].__doc__)
parser.add_argument("input_file", help="The fasta file to process", type=str)
args = parser.parse_args()
input_path = args.input_file

# Run the pipeline #
analysis = seqenv.Analysis(input_path)
analysis.run()